### ISSUE TITLE
json format: TypeError: Cannot read property 'content' of null

### ISSUE THREAD

**Issue by tamtt3** [mulesoft/mulesoft-docs#1621]
I receive below exception when I try to get cluster in json format with following command:
- runtime-mgr cluster list -o json
Notes: there are no error when I using text format or table format.

CLI v2.0.6
Connecting to the Anypoint Platform...
> runtime-mgr cluster list -o json
Error: Cannot read property 'content' of null, stack: TypeError: Cannot read property 'content' of null
    at /usr/lib/node_modules/anypoint-cli/src/table.js:293:27
    at Array.forEach (native)
    at /usr/lib/node_modules/anypoint-cli/src/table.js:290:13
    at Table.forEach (native)
    at getArrayData (/usr/lib/node_modules/anypoint-cli/src/table.js:287:9)
    at Table.toStringJSON (/usr/lib/node_modules/anypoint-cli/src/table.js:255:12)
    at Table.toString (/usr/lib/node_modules/anypoint-cli/src/table.js:135:19)
    at CommandInstance._log (/usr/lib/node_modules/anypoint-cli/src/vorpal.js:73:25)
    at /usr/lib/node_modules/anypoint-cli/src/commands/arm/cluster.js:30:14
    at tryCatcher (/usr/lib/node_modules/anypoint-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/anypoint-cli/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/anypoint-cli/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/lib/node_modules/anypoint-cli/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/lib/node_modules/anypoint-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/anypoint-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/anypoint-cli/node_modules/bluebird/js/main/async.js:15:14)

**Comment by george-hoffer** [comment]
Hi Tam, Thank you for wanting to improve MuleSoft documentation. If this error is in a MuleSoft document, please indicate the URL where the error is. Otherwise, if you are experiencing this error in relation to your use of MuleSoft software, please open a customer support case at https://support.mulesoft.com/ - you can also use this URL to view the knowledge base. You may also want to ask your question in the MuleSoft forums also can get you help diagnosing this issue. The Forums are at https://forums.mulesoft.com/index.html.

**Comment by george-hoffer** [comment]
Haven't heard back from reporter. Closing issue.
